# Generated by Django 4.1.2 on 2023-03-22 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, null=True)),
                ('name', models.TextField(max_length=100)),
                ('city', models.TextField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('password', models.CharField(max_length=32)),
            ],
            managers=[
                ('empauth', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('username', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.school')),
            ],
        ),
    ]
