# Generated by Django 4.1.2 on 2023-03-23 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
    ]
