# Generated by Django 4.1.2 on 2023-03-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_alter_school_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
