# Generated by Django 4.1.2 on 2023-03-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
