# Generated by Django 4.1.2 on 2023-04-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Budget', models.IntegerField()),
                ('Description', models.CharField(max_length=200)),
                ('Genres', models.CharField(max_length=50)),
                ('Popularity', models.FloatField(max_length=20)),
                ('Revenue', models.IntegerField()),
                ('Duration', models.IntegerField()),
                ('Language', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Release_Date', models.DateField()),
            ],
        ),
    ]
