# Generated by Django 4.1.2 on 2023-01-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginform',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
