# Generated by Django 4.1.2 on 2023-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_Interface', '0003_loginform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='loginform',
            name='user',
        ),
        migrations.AddField(
            model_name='loginform',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='loginform',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginform',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
