# Generated by Django 4.1.2 on 2023-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='coffee',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
